// ── Photo type ────────────────────────────────────────────────────────────────
export interface Photo {
  slug: string
  src: string
  alt: string
  title: string
  series: string
  aspectRatio: string
  year: number
  featured?: boolean
  cover?: boolean
  hidden?: boolean
  print?: boolean
  vimeoUrl?: string
}

// ── Series list ───────────────────────────────────────────────────────────────
export const SERIES = [
  'Architecture',
  'Urban Extracts',
  'Street',
  'Endless Pane',
  'Around the Corner',
  'Still Life',
  'Clasped',
  'Self-Portraits',
  'Abstract',
] as const

// ── Photos ────────────────────────────────────────────────────────────────────
export const photos: Photo[] = [
  {
    slug: 'urban-crown-shyness',
    src: '/images/architecture/urban-crown-shyness.jpg',
    alt: 'Urban Crown Shyness',
    title: 'Urban Crown Shyness',
    series: 'Architecture',
    aspectRatio: '2/3',
    year: 2026,
    print: true,
    featured: true,
  },
  {
    slug: 'moons-edge',
    src: '/images/street/moons-edge-left.jpg',
    alt: "Alone at the Moon's Edge",
    title: "At Moon's Edge",
    series: 'Urban Extracts',
    aspectRatio: '2/3',
    year: 2026,
    print: true,
    featured: true,
    cover: true,
  },
  
  {
    slug: 'colors-of-cdmx-001-2025',
    src: '/images/architecture/1-DSCF5662.jpg',
    alt: 'Museo Casa Estudio Frida Kahlo',
    title: 'Colors of CDMX 002',
    series: 'Architecture',
    aspectRatio: '2/3',
    year: 2025,
    print: true,
    featured: true,
  },
  {
    slug: 'colors-of-cdmx-002-2025',
    src: '/images/architecture/2-DSCF5685.jpg',
    alt: 'Museo Casa Estudio Diego Rivera',
    title: 'Colors of CDMX 001',
    series: 'Architecture',
    aspectRatio: '2/3',
    year: 2025,
    print: true,
    featured: true,
    cover: true,
  },
  {
    slug: 'colors-of-cdmx-003-2025',
    src: '/images/architecture/3-DSCF5699.jpg',
    alt: 'Diego Rivera 118',
    title: 'Colors of CDMX 003',
    series: 'Architecture',
    aspectRatio: '2/3',
    year: 2025,
    print: true,
    featured: true,
  },
  {
    slug: 'endless-pain-001-2025',
    src: '/images/endless-pane/1-DSCF6661.jpg',
    alt: 'Endless Pain 001',
    title: 'Endless Pain 001',
    series: 'Endless Pane',
    aspectRatio: '2/3',
    year: 2025,
    print: true,
    hidden: true,
  },
  {
    slug: 'endless-pane-002-2025',
    src: '/images/endless-pane/2-DSCF6737.jpg',
    alt: 'Endless Pane 002',
    title: 'Endless Pane 002',
    series: 'Endless Pane',
    aspectRatio: '2/3',
    year: 2025,
    hidden: true,
  },
  {
    slug: 'endless-pane-003-2025',
    src: '/images/endless-pane/3-DSCF7717.jpg',
    alt: 'Endless Pane 003',
    title: 'Endless Pane 003',
    series: 'Endless Pane',
    aspectRatio: '2/3',
    year: 2025,
    print: true,
    hidden: true,
  },
  {
    slug: 'endless-pane-004-2026',
    src: '/images/endless-pane/4-DSCF2100.jpg',
    alt: 'Endless Pane 004',
    title: 'Endless Pane 004',
    series: 'Endless Pane',
    aspectRatio: '2/3',
    year: 2026,
    hidden: true,
  },
  {
    slug: 'endless-pane-005-2026',
    src: '/images/endless-pane/5-DSCF2106.jpg',
    alt: 'Endless Pane 005',
    title: 'Endless Pane 005',
    series: 'Endless Pane',
    aspectRatio: '2/3',
    year: 2026,
    print: true,
    hidden: true,
  },
  {
    slug: 'endless-pane-006-2026',
    src: '/images/endless-pane/6-DSCF2243.jpg',
    alt: 'Endless Pane 006',
    title: 'Endless Pane 006',
    series: 'Endless Pane',
    aspectRatio: '2/3',
    year: 2026,
    hidden: true,
  },
  {
    slug: 'alwyn-court-2025',
    src: '/images/architecture/1-DSCF4384.jpg',
    alt: 'Alwyn Court',
    title: 'Alwyn Court',
    series: 'Architecture',
    aspectRatio: '2/3',
    year: 2025,
    print: true,
    featured: true,
  },
  {
    slug: 'drops-from-above-2025',
    src: '/images/architecture/2-DSCF7376.jpg',
    alt: 'Drops From Above',
    title: 'Drops From Above',
    series: 'Architecture',
    aspectRatio: '2/3',
    year: 2025,
    featured: true,
  },
  {
    slug: 'impenetrable-2025',
    src: '/images/architecture/3-DSCF9491.jpg',
    alt: 'Impenetrable',
    title: 'Impenetrable',
    series: 'Architecture',
    aspectRatio: '2/3',
    year: 2025,
  },
  {
    slug: 'budapest-001-2025',
    src: '/images/architecture/4-DSCF0315.jpg',
    alt: 'Budapest 001',
    title: 'Budapest 001',
    series: 'Architecture',
    aspectRatio: '2/3',
    year: 2025,
  },
  {
    slug: 'shadow-castle-2025',
    src: '/images/architecture/5-DSCF0354.jpg',
    alt: 'Shadow Castle',
    title: 'Shadow Castle',
    series: 'Architecture',
    aspectRatio: '2/3',
    year: 2025,
  },
  {
    slug: 'parked-2025',
    src: '/images/architecture/6-DSCF1047.jpg',
    alt: 'Parked',
    title: 'Parked',
    series: 'Architecture',
    aspectRatio: '1',
    year: 2025,
    hidden: true,
  },
  {
    slug: 'in-progress-2026',
    src: '/images/architecture/7-DSCF2259.jpg',
    alt: 'In Progress',
    title: 'In Progress',
    series: 'Architecture',
    aspectRatio: '2/3',
    year: 2026,
  },
  {
    slug: 'sp001-2025',
    src: '/images/personal-projects/DSCF1596.jpg',
    alt: 'SP001',
    title: 'SP001',
    series: 'Self-Portraits',
    aspectRatio: '2/3',
    year: 2025,
  },
  {
    slug: 'sp002-2025',
    src: '/images/personal-projects/Untitled design.jpg',
    alt: 'SP002',
    title: 'SP002',
    series: 'Self-Portraits',
    aspectRatio: '2/3',
    year: 2025,
  },
  {
    slug: 'sp003-2025',
    src: '/images/personal-projects/DSCF1587.jpg',
    alt: 'SP003',
    title: 'SP003',
    series: 'Self-Portraits',
    aspectRatio: '2/3',
    year: 2025,
  },
  {
    slug: 'sp004-2025',
    src: '/images/personal-projects/DSCF1667.jpg',
    alt: 'SP004',
    title: 'SP004',
    series: 'Self-Portraits',
    aspectRatio: '2/3',
    year: 2025,
  },
  {
    slug: 'atc-001-2025',
    src: '/images/around-the-corner/1-DSCF5200.jpg',
    alt: 'ATC 001',
    title: 'ATC 001',
    series: 'Around the Corner',
    aspectRatio: '2/3',
    year: 2025,
  },
  {
    slug: 'atc-002-2025',
    src: '/images/around-the-corner/2-DSCF7430.jpg',
    alt: 'ATC 002',
    title: 'ATC 002',
    series: 'Around the Corner',
    aspectRatio: '2/3',
    year: 2025,
  },
  {
    slug: 'atc-003-2025',
    src: '/images/around-the-corner/3-DSCF7585.jpg',
    alt: 'ATC 003',
    title: 'ATC 003',
    series: 'Around the Corner',
    aspectRatio: '2/3',
    year: 2025,
  },
  {
    slug: 'atc-004-2025',
    src: '/images/around-the-corner/4-DSCF8093.jpg',
    alt: 'ATC 004',
    title: 'ATC 004',
    series: 'Around the Corner',
    aspectRatio: '2/3',
    year: 2025,
    print: true,
    featured: true,
  },
  {
    slug: 'atc-005-2025',
    src: '/images/around-the-corner/5-DSCF8127.jpg',
    alt: 'ATC 005',
    title: 'ATC 005',
    series: 'Around the Corner',
    aspectRatio: '2/3',
    year: 2025,
    print: true,
    featured: true,
    cover: true,
  },
  {
    slug: 'atc-006-2025',
    src: '/images/around-the-corner/6-DSCF8233.jpg',
    alt: 'ATC 006',
    title: 'ATC 006',
    series: 'Around the Corner',
    aspectRatio: '2/3',
    year: 2025,
  },
  {
    slug: 'atc-007-2025',
    src: '/images/architecture/7-DSCF8234.jpg',
    alt: 'ATC 007',
    title: 'ATC 007',
    series: 'Around the Corner',
    aspectRatio: '2/3',
    year: 2025,
  },
  {
    slug: 'atc-007-2026',
    src: '/images/around-the-corner/8-DSCF9486.jpg',
    alt: 'ATC 007',
    title: 'ATC 007',
    series: 'Around the Corner',
    aspectRatio: '2/3',
    year: 2026,
    featured: true,
  },
  {
    slug: 'clasped-001-2026',
    src: '/images/clasped/DSCF2584.jpg',
    alt: 'Clasped 001',
    title: 'Clasped 001',
    series: 'Clasped',
    aspectRatio: '2/3',
    year: 2026,
    print: true,
    featured: true,
    cover: true,
  },
  
  {
    slug: 'clasped-003-2026',
    src: '/images/clasped/DSCF2677.jpg',
    alt: 'Clasped 003',
    title: 'Clasped 003',
    series: 'Clasped',
    aspectRatio: '2/3',
    year: 2026,
    featured: true,
  },
  
  
  {
    slug: 'still-life-001-2026',
    src: '/images/still-life/DSCF1967.jpg',
    alt: 'Still Life 001',
    title: 'Still Life 001',
    series: 'Still Life',
    aspectRatio: '2/3',
    year: 2026,
    print: true,
    featured: true,
    cover: true,
  },
  {
    slug: 'crimson-bridge-2026',
    src: '/images/street/DSCF1873.jpg',
    alt: 'Crimson Bridge',
    title: 'Crimson Bridge',
    series: 'Urban Extracts',
    aspectRatio: '2/3',
    year: 2026,
    print: true,
    featured: true,
  },
  
  
  {
    slug: 'clasped-002-2026',
    src: '/images/clasped/DSCF2651 (2).jpg',
    alt: 'Clasped 002',
    title: 'Clasped 002',
    series: 'Clasped',
    aspectRatio: '2/3',
    year: 2026,
    featured: true,
  },
  {
    slug: 'ep-001-2025',
    src: '/images/endless-pane/1-DSCF6661.jpg',
    alt: 'EP 001',
    title: 'EP 001',
    series: 'Endless Pane',
    aspectRatio: '2/3',
    year: 2025,
    featured: true,
  },
  {
    slug: 'ep-002-2026',
    src: '/images/endless-pane/3-DSCF7717.jpg',
    alt: 'Ep 002',
    title: 'Ep 002',
    series: 'Endless Pane',
    aspectRatio: '2/3',
    year: 2026,
    featured: true,
  },
  {
    slug: 'ep-003-2026',
    src: '/images/endless-pane/2-DSCF6737.jpg',
    alt: 'EP 003',
    title: 'EP 003',
    series: 'Endless Pane',
    aspectRatio: '2/3',
    year: 2026,
  },
  {
    slug: 'ep-004-2026',
    src: '/images/architecture/DSCF2100.jpg',
    alt: 'EP 004',
    title: 'EP 004',
    series: 'Endless Pane',
    aspectRatio: '2/3',
    year: 2026,
  },
  {
    slug: 'ep-005-2026',
    src: '/images/architecture/DSCF2106.jpg',
    alt: 'Ep 005',
    title: 'Ep 005',
    series: 'Endless Pane',
    aspectRatio: '2/3',
    year: 2026,
    featured: true,
  },
  {
    slug: 'ep-006-2026',
    src: '/images/architecture/DSCF2243.jpg',
    alt: 'EP 006',
    title: 'EP 006',
    series: 'Endless Pane',
    aspectRatio: '2/3',
    year: 2026,
  },
  {
    slug: 'cycling-001-2025',
    src: '/images/street/DSCF7382 (1).jpg',
    alt: 'Cycling 001',
    title: 'Cycling 001',
    series: 'Urban Extracts',
    aspectRatio: '2/3',
    year: 2025,
    print: true,
    featured: true,
  },
  {
    slug: 'pigeon-holed-2026',
    src: '/images/urban-extracts/DSCF2433.jpg',
    alt: 'Pigeon Holed',
    title: 'Pigeon Holed',
    series: 'Urban Extracts',
    aspectRatio: '2/3',
    year: 2026,
    print: true,
    featured: true,
  },
  {
    slug: 'still-life-002-2025',
    src: '/images/still-life/DSCF1477.jpg',
    alt: 'Still Life 002',
    title: 'Still Life 002',
    series: 'Still Life',
    aspectRatio: '2/3',
    year: 2025,
    featured: true,
  },
  {
    slug: 'still-life-003-2025',
    src: '/images/architecture/DSCF1480.jpg',
    alt: 'Still Life 003',
    title: 'Still Life 003',
    series: 'Still Life',
    aspectRatio: '2/3',
    year: 2025,
  },
  {
    slug: 'still-life-004-2026',
    src: '/images/still-life/DSCF1993.jpg',
    alt: 'Still Life 004',
    title: 'Still Life 004',
    series: 'Still Life',
    aspectRatio: '2/3',
    year: 2026,
  },
  {
    slug: 'still-life-005-2026',
    src: '/images/still-life/DSCF1992.jpg',
    alt: 'Still Life 005',
    title: 'Still Life 005',
    series: 'Still Life',
    aspectRatio: '2/3',
    year: 2026,
  },
  {
    slug: 'anua-pomegranate-2026',
    src: '/images/architecture/DSCF1954.jpg',
    alt: 'Anua - Pomegranate',
    title: 'Anua - Pom',
    series: 'Still Life',
    aspectRatio: '2/3',
    year: 2026,
  },
  {
    slug: 'still-life-006-2026',
    src: '/images/still-life/DSCF1496.jpg',
    alt: 'Still Life 006',
    title: 'Still Life 006',
    series: 'Still Life',
    aspectRatio: '2/3',
    year: 2026,
  },
  {
    slug: 'the-o-2026',
    src: '/images/still-life/DSCF2019.jpg',
    alt: 'The O',
    title: 'The O',
    series: 'Still Life',
    aspectRatio: '2/3',
    year: 2026,
  },
  {
    slug: 'reflect-amouge-2026',
    src: '/images/self-portraits/DSCF1933.jpg',
    alt: 'Reflect - Amouge',
    title: 'Reflect - Amouge',
    series: 'Still Life',
    aspectRatio: '2/3',
    year: 2026,
    featured: true,
  },
  {
    slug: 'barbed-2026',
    src: '/images/urban-extracts/DSCF7276.jpg',
    alt: 'Barbed',
    title: 'Barbed',
    series: 'Urban Extracts',
    aspectRatio: '2/3',
    year: 2026,
    featured: true,
  },
  {
    slug: 'the-path-2026',
    src: '/images/architecture/DSCF2718.jpg',
    alt: 'The Path',
    title: 'The Path',
    series: 'Urban Extracts',
    aspectRatio: '2/3',
    year: 2026,
    featured: true,
  },
  {
    slug: 'flipped-2026',
    src: '/images/urban-extracts/DSCF6260.jpg',
    alt: 'Flipped',
    title: 'Flipped',
    series: 'Urban Extracts',
    aspectRatio: '2/3',
    year: 2026,
  },
  
  {
    slug: 'fountain-2026',
    src: '/images/urban-extracts/FA3AF6CA-F475-4F00-9091-4A88ECD9E2F2.jpg',
    alt: 'Fountain',
    title: 'Fountain',
    series: 'Urban Extracts',
    aspectRatio: '3/2',
    year: 2026,
  },
  {
    slug: 'light-shines-no-further-2026',
    src: '/images/urban-extracts/463BB54E-4A4A-4E3C-AC1F-12FAD47E6B8F.jpg',
    alt: 'Light Shines No Further',
    title: 'Light Shines No Further',
    series: 'Urban Extracts',
    aspectRatio: '2/3',
    year: 2026,
  },
  {
    slug: 'fading-2026',
    src: '/images/street/DSCF8183.jpg',
    alt: 'Fading',
    title: 'Fading',
    series: 'Street',
    aspectRatio: '2/3',
    year: 2026,
  },
  {
    slug: 'silv-2026',
    src: '/images/around-the-corner/DSCF2713.jpg',
    alt: 'Silv',
    title: 'Silv',
    series: 'Around the Corner',
    aspectRatio: '2/3',
    year: 2026,
  },
  {
    slug: 'pensive-2025',
    src: '/images/street/DSCF0649.jpg',
    alt: 'Pensive',
    title: 'Pensive',
    series: 'Street',
    aspectRatio: '2/3',
    year: 2025,
  },
  {
    slug: 'witness-2025',
    src: '/images/architecture/DSCF0596.jpg',
    alt: 'Witness',
    title: 'Witness',
    series: 'Street',
    aspectRatio: '2/3',
    year: 2025,
  },
  {
    slug: 'flow-2025',
    src: '/images/street/DSCF9820.jpg',
    alt: 'Flow',
    title: 'Flow',
    series: 'Street',
    aspectRatio: '2/3',
    year: 2025,
  },
  {
    slug: 'trapped-2025',
    src: '/images/street/DSCF0702.jpg',
    alt: 'Trapped',
    title: 'Trapped',
    series: 'Street',
    aspectRatio: '2/3',
    year: 2025,
  },
  {
    slug: 'peaking-into-their-future-2025',
    src: '/images/street/DSCF0831.jpg',
    alt: 'Peaking Into Their Future',
    title: 'Peaking Into Their Future',
    series: 'Street',
    aspectRatio: '3/2',
    year: 2025,
  },
  {
    slug: 'analog-slog-2025',
    src: '/images/street/DSCF2289.jpg',
    alt: 'Analog Slog',
    title: 'Analog Slog',
    series: 'Street',
    aspectRatio: '3/2',
    year: 2025,
  },
  {
    slug: 'ponder-2025',
    src: '/images/street/DSCF1304.jpg',
    alt: 'Ponder',
    title: 'Ponder',
    series: 'Street',
    aspectRatio: '2/3',
    year: 2025,
  },
  {
    slug: 'now-is-now-2025',
    src: '/images/street/DSCF9142.jpg',
    alt: 'Now is Now',
    title: 'Now is Now',
    series: 'Street',
    aspectRatio: '2/3',
    year: 2025,
  },
  {
    slug: 'reflections-2026',
    src: '/images/street/DSCF2690.jpg',
    alt: 'Reflections',
    title: 'Reflections',
    series: 'Street',
    aspectRatio: '3/2',
    year: 2026,
  },
  {
    slug: 'fated-2025',
    src: '/images/architecture/DSCF0300.jpg',
    alt: 'Fated',
    title: 'Fated',
    series: 'Architecture',
    aspectRatio: '2/3',
    year: 2025,
  },
]

// ── Helpers ───────────────────────────────────────────────────────────────────
export const getFeatured = () => photos.filter(p => p.featured)
export const getCover = () => photos.filter(p => p.cover)
export const getBySeries = (series: string) => photos.filter(p => p.series === series)