// ── Photo type ────────────────────────────────────────────────────────────────
export interface Photo {
  slug: string
  src: string
  alt: string
  title: string
  series: string
  aspectRatio: string
  year: number
  featured?: boolean
  cover?: boolean
}

// ── Series list ───────────────────────────────────────────────────────────────
export const SERIES = [
  'Architecture',
  'Street',
  'Endless Pane',
  'Still Life',
  'Self-Portraits',
  'Abstract',
  'Around the Corner',
  'Clasped',
] as const

// ── Photos ────────────────────────────────────────────────────────────────────
export const photos: Photo[] = [
  {
    slug: 'urban-crown-shyness',
    src: '/images/architecture/urban-crown-shyness.jpg',
    alt: 'Urban Crown Shyness',
    title: 'Urban Crown Shyness',
    series: 'Architecture',
    aspectRatio: '2/3',
    year: 2026,
  },
  {
    slug: 'moons-edge',
    src: '/images/street/moons-edge-left.jpg',
    alt: "Alone at the Moon's Edge",
    title: "At Moon's Edge",
    series: 'Street',
    aspectRatio: '2/3',
    year: 2026,
    featured: true,
    cover: true,
  },
  {
    slug: 'crimson-bridge-v2',
    src: '/images/street/crimson-bridge-v2.jpg',
    alt: "Crimson Bridge",
    title: "Crimson Bridge",
    series: 'Street',
    aspectRatio: '2/3',
    year: 2026,
    featured: true,
  },
  {
    slug: 'colors-of-cdmx-001-2025',
    src: '/images/architecture/1-DSCF5662.jpg',
    alt: 'Museo Casa Estudio Frida Kahlo',
    title: 'Colors of CDMX 001',
    series: 'Architecture',
    aspectRatio: '2/3',
    year: 2025,
  },
  {
    slug: 'colors-of-cdmx-002-2025',
    src: '/images/architecture/2-DSCF5685.jpg',
    alt: 'Museo Casa Estudio Diego Rivera',
    title: 'Colors of CDMX 002',
    series: 'Architecture',
    aspectRatio: '2/3',
    year: 2025,
    featured: true,
    cover: true,
  },
  {
    slug: 'colors-of-cdmx-003-2025',
    src: '/images/architecture/3-DSCF5699.jpg',
    alt: 'Diego Rivera 118',
    title: 'Colors of CDMX 003',
    series: 'Architecture',
    aspectRatio: '2/3',
    year: 2025,
  },
  {
    slug: 'endless-pain-001-2025',
    src: '/images/endless-pane/1-DSCF6661.jpg',
    alt: 'Endless Pain 001',
    title: 'Endless Pain 001',
    series: 'Endless Pane',
    aspectRatio: '2/3',
    year: 2025,
  },
  {
    slug: 'endless-pane-002-2025',
    src: '/images/endless-pane/2-DSCF6737.jpg',
    alt: 'Endless Pane 002',
    title: 'Endless Pane 002',
    series: 'Endless Pane',
    aspectRatio: '2/3',
    year: 2025,
  },
  {
    slug: 'endless-pane-003-2025',
    src: '/images/endless-pane/3-DSCF7717.jpg',
    alt: 'Endless Pane 003',
    title: 'Endless Pane 003',
    series: 'Endless Pane',
    aspectRatio: '2/3',
    year: 2025,
    cover: true,
  },
  {
    slug: 'endless-pane-004-2026',
    src: '/images/endless-pane/4-DSCF2100.jpg',
    alt: 'Endless Pane 004',
    title: 'Endless Pane 004',
    series: 'Endless Pane',
    aspectRatio: '2/3',
    year: 2026,
  },
  {
    slug: 'endless-pane-005-2026',
    src: '/images/endless-pane/5-DSCF2106.jpg',
    alt: 'Endless Pane 005',
    title: 'Endless Pane 005',
    series: 'Endless Pane',
    aspectRatio: '2/3',
    year: 2026,
    featured: true,
  },
  {
    slug: 'endless-pane-006-2026',
    src: '/images/endless-pane/6-DSCF2243.jpg',
    alt: 'Endless Pane 006',
    title: 'Endless Pane 006',
    series: 'Endless Pane',
    aspectRatio: '2/3',
    year: 2026,
  },
  {
    slug: 'alwyn-court-2025',
    src: '/images/architecture/1-DSCF4384.jpg',
    alt: 'Alwyn Court',
    title: 'Alwyn Court',
    series: 'Architecture',
    aspectRatio: '2/3',
    year: 2025,
    featured: true,
  },
  {
    slug: 'drops-from-above-2025',
    src: '/images/architecture/2-DSCF7376.jpg',
    alt: 'Drops From Above',
    title: 'Drops From Above',
    series: 'Architecture',
    aspectRatio: '2/3',
    year: 2025,
  },
  {
    slug: 'impenetrable-2025',
    src: '/images/architecture/3-DSCF9491.jpg',
    alt: 'Impenetrable',
    title: 'Impenetrable',
    series: 'Architecture',
    aspectRatio: '2/3',
    year: 2025,
  },
  {
    slug: 'budapest-001-2025',
    src: '/images/architecture/4-DSCF0315.jpg',
    alt: 'Budapest 001',
    title: 'Budapest 001',
    series: 'Architecture',
    aspectRatio: '2/3',
    year: 2025,
    featured: true,
  },
  {
    slug: 'shadow-castle-2025',
    src: '/images/architecture/5-DSCF0354.jpg',
    alt: 'Shadow Castle',
    title: 'Shadow Castle',
    series: 'Architecture',
    aspectRatio: '2/3',
    year: 2025,
  },
  {
    slug: 'parked-2025',
    src: '/images/architecture/6-DSCF1047.jpg',
    alt: 'Parked',
    title: 'Parked',
    series: 'Architecture',
    aspectRatio: '1',
    year: 2025,
    featured: true,
  },
  {
    slug: 'in-progress-2026',
    src: '/images/architecture/7-DSCF2259.jpg',
    alt: 'In Progress',
    title: 'In Progress',
    series: 'Architecture',
    aspectRatio: '2/3',
    year: 2026,
  },
  {
    slug: 'sp001-2025',
    src: '/images/personal-projects/DSCF1596.jpg',
    alt: 'SP001',
    title: 'SP001',
    series: 'Self-Portraits',
    aspectRatio: '2/3',
    year: 2025,
  },
  {
    slug: 'sp002-2025',
    src: '/images/personal-projects/Untitled design.jpg',
    alt: 'SP002',
    title: 'SP002',
    series: 'Self-Portraits',
    aspectRatio: '2/3',
    year: 2025,
    featured: true,
    cover: true,
  },
  {
    slug: 'sp003-2025',
    src: '/images/personal-projects/DSCF1587.jpg',
    alt: 'SP003',
    title: 'SP003',
    series: 'Self-Portraits',
    aspectRatio: '2/3',
    year: 2025,
  },
  {
    slug: 'sp004-2025',
    src: '/images/personal-projects/DSCF1667.jpg',
    alt: 'SP004',
    title: 'SP004',
    series: 'Self-Portraits',
    aspectRatio: '2/3',
    year: 2025,
    featured: true,
  },
  {
    slug: 'atc-001-2025',
    src: '/images/around-the-corner/1-DSCF5200.jpg',
    alt: 'ATC 001',
    title: 'ATC 001',
    series: 'Around the Corner',
    aspectRatio: '2/3',
    year: 2025,
  },
  {
    slug: 'atc-002-2025',
    src: '/images/around-the-corner/2-DSCF7430.jpg',
    alt: 'ATC 002',
    title: 'ATC 002',
    series: 'Around the Corner',
    aspectRatio: '2/3',
    year: 2025,
  },
  {
    slug: 'atc-003-2025',
    src: '/images/around-the-corner/3-DSCF7585.jpg',
    alt: 'ATC 003',
    title: 'ATC 003',
    series: 'Around the Corner',
    aspectRatio: '2/3',
    year: 2025,
  },
  {
    slug: 'atc-004-2025',
    src: '/images/around-the-corner/4-DSCF8093.jpg',
    alt: 'ATC 004',
    title: 'ATC 004',
    series: 'Around the Corner',
    aspectRatio: '2/3',
    year: 2025,
    featured: true,
  },
  {
    slug: 'atc-005-2025',
    src: '/images/around-the-corner/5-DSCF8127.jpg',
    alt: 'ATC 005',
    title: 'ATC 005',
    series: 'Around the Corner',
    aspectRatio: '2/3',
    year: 2025,
    featured: true,
    cover: true,
  },
  {
    slug: 'atc-006-2025',
    src: '/images/around-the-corner/6-DSCF8233.jpg',
    alt: 'ATC 006',
    title: 'ATC 006',
    series: 'Around the Corner',
    aspectRatio: '2/3',
    year: 2025,
  },
  {
    slug: 'atc-007-2025',
    src: '/images/architecture/7-DSCF8234.jpg',
    alt: 'ATC 007',
    title: 'ATC 007',
    series: 'Around the Corner',
    aspectRatio: '2/3',
    year: 2025,
  },
  {
    slug: 'atc-007-2026',
    src: '/images/around-the-corner/8-DSCF9486.jpg',
    alt: 'ATC 007',
    title: 'ATC 007',
    series: 'Around the Corner',
    aspectRatio: '2/3',
    year: 2026,
    featured: true,
  },
  {
    slug: 'clasped-001-2026',
    src: '/images/clasped/DSCF2584.jpg',
    alt: 'Clasped 001',
    title: 'Clasped 001',
    series: 'Clasped',
    aspectRatio: '2/3',
    year: 2026,
    featured: true,
    cover: true,
  },
  {
    slug: 'clasped-002-2026',
    src: '/images/clasped/DSCF2651.jpg',
    alt: 'Clasped 002',
    title: 'Clasped 002',
    series: 'Clasped',
    aspectRatio: '2/3',
    year: 2026,
    featured: true,
  },
]

// ── Helpers ───────────────────────────────────────────────────────────────────
export const getFeatured = () => photos.filter(p => p.featured)
export const getCover = () => photos.filter(p => p.cover)
export const getBySeries = (series: string) => photos.filter(p => p.series === series)